package org.onekash.kashcal.domain.generator.parity

import org.junit.Test
import org.onekash.kashcal.domain.generator.parity.fixtures.AdversarialCorpus
import org.onekash.kashcal.domain.generator.parity.fixtures.CriticalBugCorpus
import org.onekash.kashcal.domain.generator.parity.fixtures.ExistingTestsCorpus
import org.onekash.kashcal.domain.generator.parity.fixtures.RfcExamplesCorpus
import org.onekash.kashcal.testutil.resolveProjectRoot
import java.io.File

/**
 * Runs the four corpus pools through both engines and overwrites three artifacts:
 *
 *   1. `app/src/test/resources/parity/baseline-librecur.json`
 *   2. `app/src/test/resources/parity/baseline-ical4j.json`
 *   3. a Markdown parity report
 *
 * The test passes whenever the artifacts are written; divergences are data, not failures.
 * [RRuleEngineBaselineTest] locks each engine's output to its baseline and fails on drift.
 *
 * The classification and RFC comparison go through [ParityHarnessRunner], whose 10-second
 * wall-clock timeout per engine call turns a hang into a Category C entry. The baseline
 * expansions call each engine directly, without that timeout.
 */
class RRuleEngineParityReportTest {

    private val allCases: List<RRuleCase> = buildList {
        addAll(RfcExamplesCorpus.cases)
        addAll(CriticalBugCorpus.cases)
        addAll(ExistingTestsCorpus.cases)
        addAll(AdversarialCorpus.cases)
    }

    @Test
    fun `run full corpus through both engines and generate report plus baselines`() {
        println("Running ${allCases.size} parity cases through both engines…")

        val libEntries = mutableListOf<Pair<RRuleCase, ExpansionResult>>()
        val icalEntries = mutableListOf<Pair<RRuleCase, ExpansionResult>>()
        val caseResults = mutableListOf<CaseResult>()
        val rfcComparisons = mutableListOf<RfcComparison>()

        for (case in allCases) {
            val result = ParityHarnessRunner.runCase(case)
            caseResults += result

            // Expand again for the baselines: runCase doesn't expose the per-engine output.
            val libResult = expandForBaseline(LibRecurParityEngine, case)
            val icalResult = expandForBaseline(ICal4jParityEngine, case)
            libEntries += case to libResult
            icalEntries += case to icalResult

            ParityHarnessRunner.rfcComparisonFor(case)?.let { rfcComparisons += it }
        }

        val projectRoot = resolveProjectRoot()
        writeBaseline(projectRoot, "librecur", libEntries)
        writeBaseline(projectRoot, "ical4j", icalEntries)
        writeReport(projectRoot, caseResults, rfcComparisons)

        // Print a summary so CI logs carry the headline numbers.
        val counts = caseResults.groupingBy { it.classification }.eachCount().toSortedMap()
        println("Classification counts: $counts (total=${caseResults.size})")
        println("RFC comparisons: ${rfcComparisons.size}; both-match=" +
            "${rfcComparisons.count { it.libRecurMatchesRfc && it.ical4jMatchesRfc }}")
    }

    private fun expandForBaseline(engine: RRuleEngine, case: RRuleCase): ExpansionResult {
        // Calls the engine directly, without ParityHarnessRunner's timeout, so a hanging case
        // hangs this test. RRuleEngineBaselineTest expands the same way, so both see the same
        // output.
        return engine.expand(case)
    }

    private fun writeBaseline(
        projectRoot: File,
        engineKey: String,
        entries: List<Pair<RRuleCase, ExpansionResult>>,
    ) {
        val dir = File(projectRoot, "app/src/test/resources/parity")
        dir.mkdirs()
        val file = File(dir, "baseline-$engineKey.json")
        val engineName = when (engineKey) {
            "librecur" -> "lib-recur"
            "ical4j" -> "ical4j"
            else -> engineKey
        }
        file.writeText(ParityBaselineCodec.encode(engineName, entries))
        println("Wrote baseline: ${file.absolutePath} (${entries.size} cases)")
    }

    private fun writeReport(
        projectRoot: File,
        caseResults: List<CaseResult>,
        rfcComparisons: List<RfcComparison>,
    ) {
        val dir = File(projectRoot, "docs")
        dir.mkdirs()
        val file = File(dir, "RRULE_ENGINE_PARITY.md")
        val markdown = buildReport(caseResults, rfcComparisons)
        file.writeText(markdown)
        println("Wrote report: ${file.absolutePath}")
    }

    private fun buildReport(
        caseResults: List<CaseResult>,
        rfcComparisons: List<RfcComparison>,
    ): String = buildString {
        appendLine(writeFindings(caseResults))
        appendLine()
        appendLine(ParityReportWriter.write(caseResults, rfcComparisons))
        appendLine()
        appendLine("---")
        appendLine()
        appendLine("## Methodology")
        appendLine()
        appendLine("Generated by `RRuleEngineParityReportTest`. Every RRULE case from the four " +
            "fixture pools (Pool A: RFC 5545 §3.8.5.3 examples, Pool B: CRITICAL-quirk reproducers, " +
            "Pool C: inputs from existing test suites, Pool D: adversarial inputs) is driven through " +
            "two engines:")
        appendLine()
        appendLine("- **lib-recur** — `org.dmfs.rfc5545` via " +
            "`org.onekash.kashcal.domain.generator.LibRecurEngine` (app-side).")
        appendLine("- **ical4j** — via `icaldav-core`'s `RRuleExpander` (library-side).")
        appendLine()
        appendLine("Each engine call is bounded by a 10-second wall-clock timeout to prevent " +
            "adversarial cases (unbounded SECONDLY/MINUTELY, open-ended range queries) from " +
            "hanging the run.")
        appendLine()
        appendLine("### Classification")
        appendLine()
        appendLine("- **A** — clear bug per RFC. Pool A case where exactly one engine matches the " +
            "RFC-spec ground truth. The other engine is wrong.")
        appendLine("- **B** — RFC ambiguity or non-Pool-A divergence. No authoritative ground truth " +
            "available, or both engines diverge from the RFC in the same direction.")
        appendLine("- **C** — scope gap. One or both engines timed out or threw an exception.")
        appendLine("- **D** — identical. Both engines produced the same set of timestamps.")
        appendLine()
    }

    private fun writeFindings(caseResults: List<CaseResult>): String = buildString {
        val byClass = caseResults.groupBy { it.classification }
        val a = byClass["A"].orEmpty()
        val b = byClass["B"].orEmpty()
        val c = byClass["C"].orEmpty()
        val d = byClass["D"].orEmpty()

        appendLine("## Findings at a glance")
        appendLine()
        appendLine("| Classification | Count | Description |")
        appendLine("| --- | --- | --- |")
        appendLine("| A | ${a.size} | Clear bug per RFC — one engine is wrong |")
        appendLine("| B | ${b.size} | RFC ambiguity or non-authoritative divergence |")
        appendLine("| C | ${c.size} | Scope gap — one or both engines errored/timed out |")
        appendLine("| D | ${d.size} | Identical output across both engines |")
        appendLine()

        if (a.isNotEmpty()) {
            appendLine("### Category A — migration-blocking bugs")
            appendLine()
            a.forEach { r ->
                appendLine("- **${r.case.name}**")
                r.analystNote?.let { appendLine("  - ${it.replace("\n", " ")}") }
            }
            appendLine()
        }

        if (c.isNotEmpty()) {
            appendLine("### Category C — error-path divergences (non-blocking, but handle at adapter layer on migration)")
            appendLine()
            c.forEach { r ->
                appendLine("- **${r.case.name}**")
                r.analystNote?.let { appendLine("  - ${it.replace("\n", " ")}") }
            }
            appendLine()
        }

        appendLine("### Recommendation")
        appendLine()
        if (a.isEmpty()) {
            appendLine("No Category A bugs. Migration to ical4j is **feasible** but not required — " +
                "the ${d.size}/${caseResults.size} agreement rate (${"%.1f".format(d.size * 100.0 / caseResults.size)}%) is strong, and Category B " +
                "divergences are either RFC-ambiguous or easily replicated at the adapter layer.")
        } else {
            appendLine("${a.size} Category A bug(s) found. Migration **blocked** pending upstream or " +
                "adapter-layer fixes. Details in Category A section above.")
        }
    }

}
