package org.onekash.kashcal.domain.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test
import org.onekash.kashcal.data.calendar_provider.DeviceCalendarInstance
import org.onekash.kashcal.data.db.entity.Calendar
import org.onekash.kashcal.data.db.entity.Event
import org.onekash.kashcal.data.db.entity.Occurrence
import org.onekash.kashcal.ui.screens.monthfull.spanIdentityKey

/**
 * Tests whether a shared `key()` built from [DisplayEvent.stableKey] can collide, and whether
 * stableKey can stand in for [spanIdentityKey], which the month-full layout dedups on.
 *
 * RFC 5545 §3.8.5.3: "Where duplicate instances are generated by the RRULE and RDATE
 * properties, only one recurrence is considered. Duplicate instances are ignored." A
 * recurrence set never holds two instances of one series at the same start, and the
 * occurrences table's unique `(event_id, start_ts)` index enforces the same. That keeps a Room
 * stableKey unique.
 */
class DisplayEventStableKeyTest {

    private val calendar = Calendar(
        id = 10L,
        accountId = 1L,
        caldavUrl = "https://example.test/cal/",
        displayName = "Cal",
        color = 0xFF2196F3.toInt(),
        isReadOnly = false
    )

    private fun roomEvent(id: Long, rrule: String? = null) = Event(
        id = id,
        uid = "uid-$id@kashcal",
        calendarId = 10L,
        title = "Event $id",
        startTs = 1_700_000_000_000L,
        endTs = 1_700_003_600_000L,
        dtstamp = 1_700_000_000_000L,
        isAllDay = false,
        rrule = rrule
    )

    private fun occurrence(eventId: Long, startTs: Long) = Occurrence(
        eventId = eventId,
        calendarId = 10L,
        startTs = startTs,
        endTs = startTs + 3_600_000L,
        startDay = 20231116,
        endDay = 20231116
    )

    private fun deviceInstance(
        instanceId: Long,
        eventId: Long,
        startTs: Long,
    ) = DeviceCalendarInstance(
        instanceId = instanceId,
        eventId = eventId,
        title = "Device $eventId",
        description = "",
        location = "",
        startTs = startTs,
        endTs = startTs + 3_600_000L,
        startDay = 20231116,
        endDay = 20231116,
        isAllDay = false,
        hasRrule = true,
        rrule = "FREQ=WEEKLY;BYDAY=MO",
        reminders = emptyList(),
        calendarId = 5L,
        calendarDisplayName = "Device Cal",
        calendarColor = 0xFFFF5722.toInt(),
        eventColor = null,
        status = 1,
        availability = 0,
        hasAlarm = false,
        selfAttendeeStatus = 0,
        isWritable = true,
        originalId = null,
        originalInstanceTime = null,
        timezone = "UTC",
        eventStartTs = startTs,
    )

    // ================= Room: no reachable collision =================

    @Test
    fun `two occurrences of one recurring series get distinct stableKeys`() {
        // A recurring series shares its event.id across every occurrence; the
        // occurrence start tells them apart. This is the case a day re-sort
        // shuffles, and the case a keyed all-day or day list must survive.
        val series = roomEvent(1L, rrule = "FREQ=DAILY;COUNT=5")
        val monday = DisplayEvent.Room(series, occurrence(1L, 1_700_000_000_000L), calendar)
        val tuesday = DisplayEvent.Room(series, occurrence(1L, 1_700_086_400_000L), calendar)

        assertNotEquals(
            "distinct occurrences of one series must not share a key()",
            monday.stableKey,
            tuesday.stableKey
        )
    }

    @Test
    fun `the only way two Room keys collide is a same-start duplicate the RFC forbids`() {
        // Identical (id, start) does collide. The rule in the class doc (RFC 5545
        // §3.8.5.3 and the unique occurrences index) keeps that input out of a real
        // occurrence set, so a keyed list depends on it.
        val series = roomEvent(1L, rrule = "FREQ=DAILY")
        val a = DisplayEvent.Room(series, occurrence(1L, 1_700_000_000_000L), calendar)
        val forbiddenDuplicate = DisplayEvent.Room(series, occurrence(1L, 1_700_000_000_000L), calendar)

        assertEquals(a.stableKey, forbiddenDuplicate.stableKey)
    }

    // ================= Device: no reachable collision =================

    @Test
    fun `distinct device instances get distinct stableKeys`() {
        // stableKey is built from instanceId, the Instances._ID, which is unique per
        // provider row.
        val first = DisplayEvent.Device(deviceInstance(instanceId = 200L, eventId = 50L, startTs = 1_700_000_000_000L))
        val second = DisplayEvent.Device(deviceInstance(instanceId = 201L, eventId = 50L, startTs = 1_700_086_400_000L))

        assertNotEquals(first.stableKey, second.stableKey)
    }

    // ================= stableKey is not spanIdentityKey =================

    @Test
    fun `stableKey and spanIdentityKey disagree for device events, so they are not interchangeable`() {
        // spanIdentityKey keys device events on (eventId, startTs); stableKey
        // keys them on instanceId. Two provider rows with the same (eventId,
        // startTs) but different instanceId collapse to one spanIdentityKey but
        // stay two stableKeys. Swapping spanIdentityKey for stableKey in the
        // month-full dedup changes which spans are drawn, so it is not a drop-in
        // replacement and must be verified per call site.
        val a = DisplayEvent.Device(deviceInstance(instanceId = 200L, eventId = 50L, startTs = 1_700_000_000_000L))
        val b = DisplayEvent.Device(deviceInstance(instanceId = 201L, eventId = 50L, startTs = 1_700_000_000_000L))

        assertEquals("spanIdentityKey collapses same (eventId, startTs)", a.spanIdentityKey(), b.spanIdentityKey())
        assertNotEquals("stableKey keeps them distinct by instanceId", a.stableKey, b.stableKey)
    }
}
