package org.onekash.kashcal.domain.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test
import org.onekash.kashcal.data.calendar_provider.DeviceCalendarInstance
import org.onekash.kashcal.data.db.entity.Calendar
import org.onekash.kashcal.data.db.entity.Event
import org.onekash.kashcal.data.db.entity.Occurrence
import org.onekash.kashcal.ui.screens.monthfull.spanIdentityKey

/**
 * Settles empirically whether a shared `key()` built from [DisplayEvent.stableKey]
 * could ever collide, and whether stableKey can stand in for the separate
 * [spanIdentityKey] the month-full layout dedups on.
 *
 * The governing spec rule is RFC 5545 §3.8.5.3: "When duplicate instances are
 * generated by the RRULE and RDATE properties, only one recurrence is
 * considered. Duplicate instances are ignored." A recurrence set therefore
 * never contains two instances of one series at the same start instant — a fact
 * the `(event_id, start_ts)` unique index on the occurrences table also
 * enforces. That is what keeps a Room stableKey unique within a single day.
 */
class DisplayEventStableKeyTest {

    private val calendar = Calendar(
        id = 10L,
        accountId = 1L,
        caldavUrl = "https://example.test/cal/",
        displayName = "Cal",
        color = 0xFF2196F3.toInt(),
        isReadOnly = false
    )

    private fun roomEvent(id: Long, rrule: String? = null) = Event(
        id = id,
        uid = "uid-$id@kashcal",
        calendarId = 10L,
        title = "Event $id",
        startTs = 1_700_000_000_000L,
        endTs = 1_700_003_600_000L,
        dtstamp = 1_700_000_000_000L,
        isAllDay = false,
        rrule = rrule
    )

    private fun occurrence(eventId: Long, startTs: Long) = Occurrence(
        eventId = eventId,
        calendarId = 10L,
        startTs = startTs,
        endTs = startTs + 3_600_000L,
        startDay = 20231116,
        endDay = 20231116
    )

    private fun deviceInstance(
        instanceId: Long,
        eventId: Long,
        startTs: Long,
    ) = DeviceCalendarInstance(
        instanceId = instanceId,
        eventId = eventId,
        title = "Device $eventId",
        description = "",
        location = "",
        startTs = startTs,
        endTs = startTs + 3_600_000L,
        startDay = 20231116,
        endDay = 20231116,
        isAllDay = false,
        hasRrule = true,
        rrule = "FREQ=WEEKLY;BYDAY=MO",
        reminders = emptyList(),
        calendarId = 5L,
        calendarDisplayName = "Device Cal",
        calendarColor = 0xFFFF5722.toInt(),
        eventColor = null,
        status = 1,
        availability = 0,
        hasAlarm = false,
        selfAttendeeStatus = 0,
        isWritable = true,
        originalId = null,
        originalInstanceTime = null,
        timezone = "UTC",
        eventStartTs = startTs,
    )

    // ================= (b) Room: no reachable collision =================

    @Test
    fun `two occurrences of one recurring series get distinct stableKeys`() {
        // A recurring series shares its event.id across every occurrence; the
        // occurrence start disambiguates them. This is the exact case a day
        // re-sort shuffles, and the case a keyed all-day/day list must survive.
        val series = roomEvent(1L, rrule = "FREQ=DAILY;COUNT=5")
        val monday = DisplayEvent.Room(series, occurrence(1L, 1_700_000_000_000L), calendar)
        val tuesday = DisplayEvent.Room(series, occurrence(1L, 1_700_086_400_000L), calendar)

        assertNotEquals(
            "distinct occurrences of one series must not share a key()",
            monday.stableKey,
            tuesday.stableKey
        )
    }

    @Test
    fun `the only way two Room keys collide is a same-start duplicate the RFC forbids`() {
        // RFC 5545 §3.8.5.3: duplicate instances (same series, same start) are
        // ignored — only one is kept — and the occurrences table's
        // (event_id, start_ts) unique index enforces the same thing. So the
        // sole input that would collide two Room stableKeys cannot occur in a
        // real occurrence set. This test documents that boundary: identical
        // (id, start) DOES collide, which is precisely why the DB/RFC rule that
        // makes it unreachable is load-bearing for a keyed list.
        val series = roomEvent(1L, rrule = "FREQ=DAILY")
        val a = DisplayEvent.Room(series, occurrence(1L, 1_700_000_000_000L), calendar)
        val forbiddenDuplicate = DisplayEvent.Room(series, occurrence(1L, 1_700_000_000_000L), calendar)

        assertEquals(a.stableKey, forbiddenDuplicate.stableKey)
    }

    // ================= (b) Device: no reachable collision =================

    @Test
    fun `distinct device instances get distinct stableKeys`() {
        // Instances._ID is unique per provider row, so two rows can never share
        // the instanceId that stableKey is built from.
        val first = DisplayEvent.Device(deviceInstance(instanceId = 200L, eventId = 50L, startTs = 1_700_000_000_000L))
        val second = DisplayEvent.Device(deviceInstance(instanceId = 201L, eventId = 50L, startTs = 1_700_086_400_000L))

        assertNotEquals(first.stableKey, second.stableKey)
    }

    // ================= (c) stableKey is NOT spanIdentityKey =================

    @Test
    fun `stableKey and spanIdentityKey disagree for device events, so they are not interchangeable`() {
        // spanIdentityKey keys device events on (eventId, startTs); stableKey
        // keys them on instanceId. These classify the same pair differently:
        // two provider rows with the same (eventId, startTs) but different
        // instanceId collapse to ONE spanIdentityKey but stay TWO stableKeys.
        // Any refactor that swaps spanIdentityKey for stableKey in the
        // month-full dedup therefore changes which spans are drawn — it is not
        // a safe drop-in replacement and must be verified per call site.
        val a = DisplayEvent.Device(deviceInstance(instanceId = 200L, eventId = 50L, startTs = 1_700_000_000_000L))
        val b = DisplayEvent.Device(deviceInstance(instanceId = 201L, eventId = 50L, startTs = 1_700_000_000_000L))

        assertEquals("spanIdentityKey collapses same (eventId, startTs)", a.spanIdentityKey(), b.spanIdentityKey())
        assertNotEquals("stableKey keeps them distinct by instanceId", a.stableKey, b.stableKey)
    }
}
