package org.onekash.kashcal.data.db.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import kotlinx.coroutines.flow.Flow
import org.onekash.kashcal.data.db.entity.AddressBook

/**
 * Data Access Object for CardDAV address-book collections.
 *
 * Provides CRUD operations and queries for the `address_books` table.
 * Mirrors [CalendarsDao] conventions.
 */
@Dao
interface AddressBookDao {

    // ========== Read Operations ==========

    /**
     * Get all address books as reactive Flow.
     */
    @Query("SELECT * FROM address_books ORDER BY display_name ASC")
    fun getAll(): Flow<List<AddressBook>>

    /**
     * Get address book by ID.
     */
    @Query("SELECT * FROM address_books WHERE id = :id")
    suspend fun getById(id: Long): AddressBook?

    /**
     * Get address book by collection URL (unique per account).
     */
    @Query("SELECT * FROM address_books WHERE account_id = :accountId AND url = :url")
    suspend fun getByAccountIdAndUrl(accountId: Long, url: String): AddressBook?

    /**
     * Get address books for a specific account (reactive).
     */
    @Query("SELECT * FROM address_books WHERE account_id = :accountId ORDER BY display_name ASC")
    fun getByAccountId(accountId: Long): Flow<List<AddressBook>>

    /**
     * Get address books for an account (one-shot).
     */
    @Query("SELECT * FROM address_books WHERE account_id = :accountId ORDER BY display_name ASC")
    suspend fun getByAccountIdOnce(accountId: Long): List<AddressBook>

    // ========== Write Operations ==========

    /**
     * Insert new address book. Returns row ID.
     */
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(addressBook: AddressBook): Long

    /**
     * Insert a new book, or update the existing one identified by its unique
     * `(account_id, url)`, returning its row id.
     *
     * This deliberately does NOT use `OnConflictStrategy.REPLACE`: REPLACE
     * delete-inserts on conflict, minting a fresh autogenerated `id` and (once a
     * child table FK-references `address_books.id`) cascade-deleting its links on
     * every re-pull. Matching on the natural key and issuing an [update] instead
     * keeps a book's `id` stable across re-syncs, as [AddressBook] documents.
     */
    @Transaction
    suspend fun upsert(addressBook: AddressBook): Long {
        val existing = getByAccountIdAndUrl(addressBook.accountId, addressBook.url)
        return if (existing == null) {
            insert(addressBook)
        } else {
            update(addressBook.copy(id = existing.id))
            existing.id
        }
    }

    /**
     * Update existing address book.
     */
    @Update
    suspend fun update(addressBook: AddressBook)

    /**
     * Delete address book.
     */
    @Delete
    suspend fun delete(addressBook: AddressBook)

    /**
     * Delete address book by ID.
     */
    @Query("DELETE FROM address_books WHERE id = :id")
    suspend fun deleteById(id: Long)

    /**
     * Delete all address books for an account.
     */
    @Query("DELETE FROM address_books WHERE account_id = :accountId")
    suspend fun deleteByAccountId(accountId: Long)

    // ========== Sync Metadata Updates ==========

    /**
     * Update sync token and ctag after sync.
     */
    @Query("UPDATE address_books SET sync_token = :syncToken, ctag = :ctag WHERE id = :id")
    suspend fun updateSyncToken(id: Long, syncToken: String?, ctag: String?)

    /**
     * Update ctag only (for servers without sync-token support).
     */
    @Query("UPDATE address_books SET ctag = :ctag WHERE id = :id")
    suspend fun updateCtag(id: Long, ctag: String?)

    /**
     * Set the per-book "sync this address book" toggle.
     */
    @Query("UPDATE address_books SET is_sync_enabled = :enabled WHERE id = :id")
    suspend fun setSyncEnabled(id: Long, enabled: Boolean)
}
