name: Mirror to Codeberg
on:
  push:
    branches: ['main']
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror
        env:
          SSH_KEY: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          git remote add codeberg git@codeberg.org:alexb936/KashCal.git
          git push codeberg main --tags --force
