package org.onekash.kashcal.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Stores one CardDAV address-book collection of an account (RFC 6352 `addressbook`
 * resourcetype), one row per synced collection. Per-contact state lives on the Contacts
 * Provider's RawContact SYNC columns, never here.
 *
 * Like [Calendar] it has an autogenerated `id` and `is_*` boolean naming, but its URL is unique
 * per account, not globally (two logins can share a collection path on different hosts). A
 * re-sync updates the row found by `(account_id, url)` instead of conflict-replacing it
 * ([org.onekash.kashcal.data.db.dao.AddressBookDao.upsert]), so a book's `id` is stable across
 * re-pulls.
 *
 * The pull and push work from each run's discovered books. The pull reads only [syncToken] and
 * [ctag] of this row; the push reads nothing from it.
 */
@Entity(
    tableName = "address_books",
    foreignKeys = [
        ForeignKey(
            entity = Account::class,
            parentColumns = ["id"],
            childColumns = ["account_id"],
            onDelete = ForeignKey.CASCADE // deleting an account drops its books
        )
    ],
    indices = [
        Index(value = ["account_id"]),
        Index(value = ["account_id", "url"], unique = true) // per-account uniqueness
    ]
)
data class AddressBook(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** Owning account; deleting the account cascades to its books. */
    @ColumnInfo(name = "account_id")
    val accountId: Long,

    /**
     * Absolute collection URL: the server's href resolved against the home URL's host, with
     * no trailing-slash normalization. Unique within the account.
     */
    @ColumnInfo(name = "url")
    val url: String,

    /** Collection `DAV:displayname`. Nothing displays it yet. */
    @ColumnInfo(name = "display_name")
    val displayName: String,

    /** RFC 6352 §6.2.1 `CARDDAV:addressbook-description`. Nothing reads it yet. */
    @ColumnInfo(name = "description")
    val description: String? = null,

    /**
     * vCard version negotiated from RFC 6352 §6.2.2 `CARDDAV:supported-address-data`. When that
     * property is absent the server must be assumed to accept only `text/vcard;version=3.0`
     * (§6.2.2), hence the "3.0" default. Nothing reads the stored value. The authoritative
     * per-object format is the `VERSION:` line in the fetched body.
     */
    @ColumnInfo(name = "vcard_version")
    val vcardVersion: String = "3.0",

    /**
     * Non-standard CalendarServer `getctag`, a cheap "did anything change?" probe. Null on
     * servers without it and until a sync of the book succeeds.
     */
    @ColumnInfo(name = "ctag")
    val ctag: String? = null,

    /**
     * RFC 6578 sync-token, the authoritative delta cursor. Null until the first sync and on
     * servers without sync-tokens.
     */
    @ColumnInfo(name = "sync_token")
    val syncToken: String? = null,

    /**
     * Whether the collection is read-only; discovery sets it as
     * [org.onekash.kashcal.sync.carddav.model.CardDavAddressBook.isReadOnly] describes.
     * Defaults to true.
     */
    @ColumnInfo(name = "is_read_only")
    val isReadOnly: Boolean = true,

    /**
     * A per-book "sync this address book" toggle. Nothing sets or reads it: the pull syncs
     * every discovered book.
     */
    @ColumnInfo(name = "is_sync_enabled")
    val isSyncEnabled: Boolean = true
)
