package org.onekash.kashcal.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * CardDAV address-book collection entity.
 *
 * Represents one address-book collection within an account (RFC 6352
 * `addressbook` resourcetype). One row per synced collection; per-contact
 * state lives on the Contacts Provider's RawContact SYNC columns, never here,
 * so there is no duplication of the provider's own per-row state.
 *
 * Mirrors the sibling [Calendar] entity: surrogate autogenerated `id` PK, URL
 * unique *per account* (two logins can legitimately share a collection path on
 * different hosts), and `is_*` boolean naming. The re-sync write path updates
 * the existing row by `(account_id, url)` rather than conflict-replacing it, so
 * a book's `id` is stable across re-pulls.
 */
@Entity(
    tableName = "address_books",
    foreignKeys = [
        ForeignKey(
            entity = Account::class,
            parentColumns = ["id"],
            childColumns = ["account_id"],
            onDelete = ForeignKey.CASCADE // deleting an account drops its books
        )
    ],
    indices = [
        Index(value = ["account_id"]),
        Index(value = ["account_id", "url"], unique = true) // per-account uniqueness
    ]
)
data class AddressBook(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Parent account ID.
     * CASCADE delete: when the account is deleted, all its books are deleted.
     */
    @ColumnInfo(name = "account_id")
    val accountId: Long,

    /**
     * Collection URL, trailing-slash-normalized. Unique within the account.
     */
    @ColumnInfo(name = "url")
    val url: String,

    /**
     * Collection display name shown in UI.
     */
    @ColumnInfo(name = "display_name")
    val displayName: String,

    /**
     * RFC 6352 §6.2.1 `CARDDAV:addressbook-description` (human-readable).
     * Optional; useful for a future book-picker UI.
     */
    @ColumnInfo(name = "description")
    val description: String? = null,

    /**
     * vCard version negotiated from RFC 6352 §6.2.2
     * `CARDDAV:supported-address-data`. Per §6.2.2, when that property is
     * absent the server MUST be assumed to accept only `text/vcard;version=3.0`
     * — hence the "3.0" default. Records the negotiated request preference so
     * the pull can request the right `address-data` version without re-probing;
     * the authoritative per-object format is the `VERSION:` line in the fetched
     * body, not this field.
     */
    @ColumnInfo(name = "vcard_version")
    val vcardVersion: String = "3.0",

    /**
     * Non-standard CalendarServer `getctag` — a cheap "did anything change?"
     * probe. Nullable: absent on some servers and unset until the first sync.
     */
    @ColumnInfo(name = "ctag")
    val ctag: String? = null,

    /**
     * RFC 6578 sync-token — the authoritative incremental cursor. Nullable: a
     * brand-new book has neither ctag nor sync-token until the first sync, and
     * not every server supports both.
     */
    @ColumnInfo(name = "sync_token")
    val syncToken: String? = null,

    /**
     * Whether the collection is read-only (server-advertised
     * `DAV:current-user-privilege-set` lacking write). Defaults true for the
     * read-only MVP.
     */
    @ColumnInfo(name = "is_read_only")
    val isReadOnly: Boolean = true,

    /**
     * The user's per-book "sync this address book" toggle.
     */
    @ColumnInfo(name = "is_sync_enabled")
    val isSyncEnabled: Boolean = true
)
